-- ========================================
-- CLEAR ALL SIGNALS - FRESH START
-- ========================================
-- This script clears all existing signals to start fresh with the new tier-aware system
-- Run this ONLY ONCE before starting production

-- 1. Backup existing signals (optional - comment out if not needed)
-- CREATE TABLE user_signals_backup AS SELECT * FROM user_signals;

-- 2. Delete all signals generated by edge function
DELETE FROM user_signals
WHERE metadata->>'generatedBy' = 'edge-function';

-- 3. Delete any other signals (manual or test signals)
-- Uncomment if you want to delete ALL signals
-- DELETE FROM user_signals;

-- 4. Reset any related tracking tables (if they exist)
-- DELETE FROM signal_outcomes WHERE signal_id IN (SELECT signal_id FROM user_signals);

-- 5. Verify deletion
SELECT
  COUNT(*) as total_signals,
  COUNT(*) FILTER (WHERE metadata->>'generatedBy' = 'edge-function') as edge_function_signals,
  COUNT(*) FILTER (WHERE tier = 'FREE') as free_signals,
  COUNT(*) FILTER (WHERE tier = 'PRO') as pro_signals,
  COUNT(*) FILTER (WHERE tier = 'MAX') as max_signals
FROM user_signals;

-- Expected result: All counts should be 0

-- 6. Check active subscriptions (ensure users exist)
SELECT
  tier,
  COUNT(*) as user_count,
  COUNT(*) FILTER (WHERE status = 'active') as active_users
FROM user_subscriptions
GROUP BY tier
ORDER BY tier;

-- This should show your active users by tier
-- FREE: X active users
-- PRO: X active users
-- MAX: X active users

-- ========================================
-- FRESH START READY!
-- ========================================
-- After running this:
-- 1. The next cron execution will generate first signals
-- 2. Each tier will get signals at their scheduled intervals
-- 3. All signals will have adaptive expiry (6-24h)
-- 4. Direction-aware deduplication will apply to future signals
