/**
 * UPGRADE PAGE
 *
 * Unified free experience — no paid tiers during user acquisition phase.
 * Redirects users to the full feature set available to everyone.
 */

import { AppHeader } from '@/components/AppHeader';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Check, Zap, Shield, Brain, Activity, AlertTriangle, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Upgrade() {
  const navigate = useNavigate();

  const features = [
    'Real-time AI trading signals',
    '17 institutional-grade strategies',
    'Full entry, stop-loss & target levels',
    'ML-powered quality filtering (Delta V2)',
    '24/7 autonomous signal generation',
    '3 AI agents trading live in Arena',
    'Signal history & performance tracking',
    'Advanced pipeline analytics',
    'Multi-timeframe analysis',
    'Regime-aware signal scoring',
  ];

  return (
    <div className="min-h-screen bg-background">
      <AppHeader />

      <div className="container mx-auto p-6 max-w-3xl">
        {/* Header */}
        <div className="text-center mb-12">
          <Badge className="mb-4 bg-gradient-to-r from-emerald-500 to-cyan-500 text-white border-0">
            EARLY ACCESS — ALL FEATURES UNLOCKED
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-emerald-400 via-cyan-400 to-blue-500 bg-clip-text text-transparent">
            Everything is Free
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            During early access, every user gets the full AI signal experience — no tiers, no limits, no paywall.
          </p>
        </div>

        {/* Single unified plan card */}
        <Card className="relative p-8 border-2 border-emerald-500/50 shadow-xl mb-8">
          <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
            <Badge className="bg-gradient-to-r from-emerald-500 to-cyan-500 text-white border-0 px-4 py-1">
              FULL ACCESS
            </Badge>
          </div>

          <div className="text-center mb-6">
            <div className="inline-flex items-center gap-2 p-3 rounded-lg bg-gradient-to-r from-emerald-500 to-cyan-500 text-white mb-4">
              <Zap className="w-6 h-6" />
              <span className="text-xl font-bold">FREE</span>
            </div>
            <div className="mb-2">
              <span className="text-5xl font-bold">$0</span>
            </div>
            <p className="text-sm text-muted-foreground">Free during early access — no credit card required</p>
          </div>

          <ul className="space-y-3 mb-8">
            {features.map((feature, index) => (
              <li key={index} className="flex items-start gap-2 text-sm">
                <Check className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                <span>{feature}</span>
              </li>
            ))}
          </ul>

          <Button
            onClick={() => navigate('/intelligence-hub')}
            className="w-full bg-gradient-to-r from-emerald-500 to-cyan-500 text-white hover:opacity-90"
            size="lg"
          >
            Go to Intelligence Hub
            <ArrowRight className="w-4 h-4 ml-2" />
          </Button>
        </Card>

        {/* AI Disclaimer */}
        <Card className="p-5 mb-8 border border-amber-500/30 bg-amber-500/5">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="font-semibold text-amber-500 text-sm mb-1">AI Learning Model — Not Financial Advice</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Signals are generated by an experimental open-source AI model currently in its learning phase.
                This is a research project — do not use these signals as the sole basis for trading decisions.
                Always do your own research and manage your risk accordingly.
              </p>
            </div>
          </div>
        </Card>

        {/* Trust indicators */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-12">
          <Card className="p-5 text-center">
            <Shield className="w-10 h-10 mx-auto mb-3 text-emerald-500" />
            <h3 className="font-semibold text-sm mb-1">Open Source</h3>
            <p className="text-xs text-muted-foreground">
              Transparent AI models and signal generation pipeline
            </p>
          </Card>

          <Card className="p-5 text-center">
            <Brain className="w-10 h-10 mx-auto mb-3 text-cyan-500" />
            <h3 className="font-semibold text-sm mb-1">17 Strategies</h3>
            <p className="text-xs text-muted-foreground">
              Institutional-grade AI models across multiple timeframes
            </p>
          </Card>

          <Card className="p-5 text-center">
            <Activity className="w-10 h-10 mx-auto mb-3 text-blue-500" />
            <h3 className="font-semibold text-sm mb-1">Real-Time</h3>
            <p className="text-xs text-muted-foreground">
              24/7 autonomous signal generation and monitoring
            </p>
          </Card>
        </div>

        {/* Enterprise CTA */}
        <Card className="p-8 text-center border border-border/50">
          <h2 className="text-xl font-bold mb-2">Need API Access?</h2>
          <p className="text-sm text-muted-foreground mb-4">
            For institutions and developers who want to integrate our AI signals into their own systems.
          </p>
          <Button
            variant="outline"
            onClick={() => window.location.href = 'mailto:contact@quantumx.org.in?subject=Enterprise API Access Inquiry'}
          >
            Contact Us for Enterprise
          </Button>
        </Card>
      </div>
    </div>
  );
}
